config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :actors do
    resources :comments, module: :actors
  end
  resources :films do
    resources :comments, module: :films
  end

  root 'films#index'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :comments, as: :commentable

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :actors
  has_many :comments, as: :commentable

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/actors/comments_controller.rb
class Actors::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Actor.find(params[:actor_id])
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :description, :image, :film_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.create comment_params
    @comment.user_id = current_user
    @comment.save
    redirect_to @commentable, notice: 'Your comment was successfully posted.'
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/films/comments_controller.rb
class Films::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Film.find(params[:film_id])
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:image, :title, :description, :actor_id)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/actors/_form.html.erb
<%= form_for actor, html: { multipart: true } do |f| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :film_id %>
    <%= f.number_field :film_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Actor', new_actor_path, class: "btn btn-secondary float-xs-right" %>
<h1>Actors</h1>

<table style="width: 100%;" class="table table-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= image_tag actor.image.url(:thumb) %></td>
        <td><%= link_to actor.name, actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<h1><%= @actor.name %></h1>
<%= image_tag @actor.image.url(:medium) %>
<%= simple_format @actor.description %>

<%= render partial: 'comments/comment', locals: {commentable: @actor} %>
<%= render partial: 'comments/form', locals: {commentable: @actor} %>

<%= link_to 'Edit', edit_actor_path(@actor) %>
<%= link_to 'Back', actor_path %>

app/views/comments/_comment.html.erb
<h3>Comments</h3>
<% commentable.comments.each do |comment| %>
  <div class="card card-inverse">
    <%= comment.body %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%  #in case of model do next:
  #POST /films/1/comments
  #or
  #Post /actors/1/comments
%>

<%= form_for [commentable, Comment.new] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control", placeholder: 'Add a comment' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/films/_form.html.erb
<%= form_for film, html: { multipart: true } do |f| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :actor_id %>
    <%= f.number_field :actor_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Film', new_film_path, class: "btn btn-secondary float-xs-right" %>
<h1>Films</h1>

<table style="width: 100%;" class="table table-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= image_tag film.image.url(:thumb) %></td>
        <td><%= link_to film.title, film %></td>
        <td><%= link_to 'Edit', edit_film_path(film) %></td>
        <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<h1><%= @film.title %></h1>
<%= image_tag @film.image.url(:medium) %>
<%= simple_format @film.description %>

<%= render partial: 'comments/comment', locals: {commentable: @film} %>
<%= render partial: 'comments/form', locals: {commentable: @film} %>

<%= link_to 'Edit', edit_film_path(@film) %>
<%= link_to 'Back', film_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolymorphicComments</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partial/_header.html.erb
<nav class="navbar navbar-light bg-faded">
  <div class="container">
    <div class="nav navbar-nav">
      <%= link_to 'Movie Database', root_path, class: 'navbar-brand' %>
      <%= link_to 'Films', films_path, class: 'nav-item nav-link' %>
      <%= link_to 'Actors', actors_path, class: 'nav-item nav-link' %>
      
      <div class="float-xs-right">
      <% if user_signed_in? %>
        <%= link_to 'Account', edit_user_registration_path, class: 'btn btn-secondary' %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary' %>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-secondary' %>
      <% end %>
      </div>
    </div>
  </div>
</nav>